# 해당 버전은 yml 파일에 대한 문서 버전 표기며 docker engine 버전 마다 표기가 달라진다.
# https://docs.docker.com/compose/compose-file/compose-versioning/

version: "3.8"                                          # 파일 규격 버전
services:                                               # 컨테이너의 집합체, 이곳에 실행하려는 컨테이너들을 정의
  redis-master:                        # 서비스 명(네트워크 호스트명) / 같은 네트워크에 속한 컨테이너끼리 서비스 명으로 접근 가능
    container_name: redis-master
    image: redis:6
    ports:                                              # 접근 포트 설정(호스트 port : 컨테이너 port)
      - "6379:6379"
  redis-slave:                        # 서비스 명(네트워크 호스트명) / 같은 네트워크에 속한 컨테이너끼리 서비스 명으로 접근 가능
    container_name: redis-slave
    image: redis:6
    ports:                                              # 접근 포트 설정(호스트 port : 컨테이너 port)
      - "6380:6379"
    volumes:
      - ./redis/conf:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/redis.conf