spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE} # default
    group:
      local:
        - common
      prod:
        - common
---
server:
  port: 80

spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379


---
spring:
  config:
    activate:
      on-profile: common


---
spring:
  config:
    activate:
      on-profile: prod

redis:
  sentinel:
    hostname: redis_kafka-redis-sentinel
    imageCount: 3
    port: 26379

